local opt = vim.opt

opt.number = true
opt.relativenumber = false
opt.mouse = ''
opt.ignorecase = true
opt.smartcase = true
opt.termguicolors = true
opt.cmdheight = 0
opt.completeopt = { 'menu', 'menuone', 'noselect' }
opt.showmode = false
opt.showcmd = false
opt.updatetime = 250
opt.signcolumn = 'yes'
opt.clipboard = 'unnamedplus'
opt.splitright = true
opt.splitbelow = true
opt.expandtab = true
opt.shiftwidth = 2
opt.tabstop = 2
